Disable tests for Windows
Summary:
Tests still fail on Windows due to:
```
Run npm test

> tree-sitter-erlang@0.0.0 test
> node --test bindings/node/*_test.js

Could not find 'D:\a\tree-sitter-erlang\tree-sitter-erlang\bindings\node\*_test.js'
Error: Process completed with exit code 1.
```

I am not familiar with the setup, so disabling the tests on Windows for now to get a green CI. If you know what could cause the issue, please advise.

Reviewed By: alanz

Differential Revision: D69656486

fbshipit-source-id: d44ffcd787368db2f97696011c87a2b33336206b